name: CD Pipeline

on: 
  workflow_dispatch:

jobs:
  build_model:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout latest version of main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn optuna joblib

      - name: Run model training script
        run: |
          python M3/m3_copy.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: best_model_artifact
          path: ${{ github.workspace }}
          retention-days: 1

  build_docker:
    runs-on: ubuntu-latest
    needs: build_model

    permissions:
      contents: write

    steps:
      - name: Retrieve saved model artifact
        uses: actions/download-artifact@v3
        with:
          name: best_model_artifact
          path: ${{ github.workspace }}

      - run: |
          ls -ltr ${{ github.workspace }}
