name: CD Pipeline

on: 
  workflow_dispatch:

jobs:
  build_model:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout latest version of main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn optuna joblib

      - name: Run model training script
        run: |
          python M3/m3_copy.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: best_model_artifact
          path: ${{ github.workspace }}
          retention-days: 1

  build_docker:
    runs-on: ubuntu-latest
    needs: build_model

    permissions:
      contents: write

    steps:
      - name: Retrieve saved model artifact
        uses: actions/download-artifact@v3
        with:
          name: best_model_artifact
          path: ${{ github.workspace }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to gitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: |
          echo "
          FROM python:3.12-slim
          WORKDIR /app
          COPY requirements.txt /app
          COPY best_model.pkl /app
          COPY scaler.pkl /app
          COPY M3/m3_flask.py /app
          RUN pip install --no-cache-dir -r requirements.txt
          EXPOSE 5000
          ENV NAME World
          CMD [\"python\", \"m3_flask.py\"]
          " > Dockerfile
          docker build -t ghcr.io/${{ github.repository_owner }}/mlopsassignment1/my-model:latest .

      - name: Push docker image to GitHub container registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/mlopsassignment1/my-model:latest

      - name: Deploy docker image
        run: |
          mkdir -p M3/deployment
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          echo "FROM ghcr.io/${{ github.repository_owner }}/mlopsassignment1/my-model:latest" > M3/deployment/Dockerfile_$TIMESTAMP
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add M3/deployment/Dockerfile_$TIMESTAMP
          git commit -m "Deploy Docker image with timestamp"
          git push origin main
