name: Lint and Merge Workflow

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint M3/m3.py
        run: |
          flake8 M3/m3.py | tee lint-output.txt
          cat lint-output.txt
        continue-on-error: true
