name: Lint and Merge Workflow

on:
  push:
    branches:
      - '2022AA05005'
    paths:
      - 'M3/m3.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Print branch
        run: |
          echo "Branch: ${{ github.ref_name }}"
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print branch and paths
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Files changed:"
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint M3/m3.py
        run: |
          flake8 M3/m3.py | tee lint-output.txt
          cat lint-output.txt
        continue-on-error: true
